apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-client
spec:
  replicas: 4
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: gcr.io/cloud-project-433315/client:latest
        ports:
        - containerPort: 9200
